let mango;
console.log(mango);
mangue = 10;
console.log(mangue);
mangue + 1;
console.log(mangue);
mangue = mangue +1;
console.log(mangue);
let banane = mangue;
console.log(banane);
banane = banane/2;
console.log(banane);
console.log(banane);
